// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqgcejxvoiinnwonwqiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZ2Nlanh2b2lpbm53b253cWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDI3MjQsImV4cCI6MjA1Nzg3ODcyNH0.-ydZ44hgCb570TMh__arY2d-MYBmpPDbtebW7D58Xlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});